set_active_sensor:
  description: Changes the active sensor for your Nest thermostat
  fields:
    entity_id: 
        description: The thermostat to operate on
        example: "climate.nest"
    sensor:
        description: The Nest temperature sensor to use instead of the one in the thermostat.  Set to "" to go back to the thermostat
        example: "sensor.bedroom_nest_sensor | \"\""
boost_hot_water:
  description: Turn boost mode on for the period of time specified, or off."
  fields:
    entity_id:
      description: Name(s) of entites to change.
      example: "water_heater.hot_water"
    time_period:
      description: Time period in minutes for the boost.
      example: 30
    boost_mode:
      description: Enable boost funcion.
      example: True
